
import Navbar from "./Navbar/page";
import Aside from "./Aside/page";
import "./globals.css";
import {ebrima} from './fonts/fonts.js'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={`main ${ebrima.className}`}>
          <Navbar/>
          <div className="content">
            {children}
            <Aside/>
          </div>
        </div>
      </body>
    </html>
  );
}
